name: IoC Deploy
on: 
    push:
     branches:
        - 'master'
    workflow_dispatch:

permissions: write-all

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pnpm install
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: prod
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cloud-url: s3://levdops-pulumi?region=eu-central-1&awssdk=v2&profile=default
      - run: "echo finished"

