name: IoC Deploy
on: 
    push:
     branches:
        - 'master'
    workflow_dispatch:

permissions: write-all

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 12
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.aws-access-key-id }}
          aws-region: ${{ env.aws-region }}
          aws-secret-access-key: ${{ env.aws-secret-access-key }}
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run npm install
        run: npm install
      - name: Setup Pulumi
        uses: pulumi/actions@v3
        with:
          command: preview
          github-token: ${{ secrets.GH_PAT }}
          work-dir: infra
